#!/usr/bin/env bash

# processnumber_segment


# append to prompt: current process number in history
# arg: $1 foreground color
# arg; $2 background color
function processnumber_segment {
    local bg_color="$1"
    local fg_color="$2"
    local content="$(( $(fc -l -1 | cut -f 1) + 1))"
    PS1+="$(segment_end $fg_color $bg_color)"
    PS1+="$(segment_content $fg_color $bg_color " $content ")"
    __last_color="$bg_color"
}
